before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: moducate
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "5"
      - "6"
      - "7"
    goos:
      - freebsd
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: macos
      "386": 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^refactor"
      - "^test"
      - "^style"
      - "^chore"
      - "^ci"
      - "^build"

release:
  github:
    owner: moducate
    name: moducate
