version: 2.1

orbs:
  code-climate: travelaudience/code-climate@0.1.2
  go: circleci/go@1.7.0

jobs:
  test:
    executor:
      name: go/default
      tag: "1.17"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

workflows:
  main:
    jobs:
      - build:
          post-steps:
            - code-climate/install
            - code-climate/format_coverage:
                coverage_file: cover-source.out
                input_type: gocov
            - code-climate/upload_coverage
