version: 2.1

orbs:
  code-climate: travelaudience/code-climate@0.1.2
  go: circleci/go@1.7.0

jobs:
  test:
    executor:
      name: go/default
      tag: "1.17"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: mkdir -p /tmp/artifacts
      - go/test:
          covermode: atomic
          failfast: true
          race: true
      - run: go tool cover -html=cover-source.out -o coverage.html
      - run: mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - run: go install github.com/jstemmer/go-junit-report
      - run: go test -v 2>&1 | go-junit-report > report.xml
      - store_test_results:
          path: report.xml

workflows:
  main:
    jobs:
      - test:
          post-steps:
            - code-climate/install
            - code-climate/format_coverage:
                additional_flags: "--prefix=github.com/moducate/moducate/"
                coverage_file: cover-source.out
                input_type: gocov
            - code-climate/upload_coverage
