name: "Nightly Docker Image"

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: moducate/moducate:nightly
