name: "Nightly Docker Image"

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - id: nightly-check
        name: Check for changes since last nightly
        uses: lukecarr/nightly-check@v0.1.0

  nightly:
    runs-on: ubuntu-latest

    needs: check
    if: ${{ needs.check.outputs.changes == 'false' }}

    steps:        
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: moducate/moducate:nightly
